### ISSUE TITLE
one problem when do the Quick Run ECO Tracker

### ISSUE THREAD

**Issue by nulidushuo** [rockkingjy/OpenTracker#10]
my platform is  Jetson TX1, ubuntu 16.04
after making changes as the guide, and cd OpenTracker/eco
make
my problem is as following:
g++ -c -o ffttools.o ffttools.cc -g -Wall `pkg-config --cflags opencv` -lstdc++ -lm -std=c++0x -O3 -fPIC  -DUSE_SIMD -msse4 -DUSE_MULTI_THREAD -isystem ../googletest/include
g++: error: unrecognized command line option ‘-msse4’
makefile:110: recipe for target 'ffttools.o' failed
make: *** [ffttools.o] Error 1

really hope to get your help

**Comment by rockkingjy** [comment]
@nulidushuo If you use Jetson Tx1, set in makefile USE_SIMD=2 will work

**Comment by rockkingjy** [comment]
@nulidushuo there are two makefiles in the depository, one is in opentracker/ root, one is in opentracker/eco, make sure to change them both and have a try.

**Comment by nulidushuo** [comment]
And the following guide should be cd OpenTracker/

Quick Run (almost) all the tracker:
git clone https://github.com/rockkingjy/OpenTracker
cd OpenTracker/kcf
make 
./trackerscompare.bin

**Comment by rockkingjy** [comment]
@nulidushuo  you are right, thanks for the correction.

**Comment by nulidushuo** [comment]
hi, sorry to disturb you again. I have run all the trackers sucessfully on the crossing images. And I want to run them on oneperson.mp4 like your demo. How can I  do that? Thanks you a lot!

**Comment by isgursoy** [comment]
You should get images (frame) from video. OpenCV can do that.
