### ISSUE TITLE
为什么我在安卓手机上用NEON优化后的程序，比没优化前的程序还慢

### ISSUE THREAD

**Issue by TCBocean** [rockkingjy/OpenTracker#11]
你好，又是我...

前段时间我还用不了NEON优化，但是看了你做的bug修复后，发现是我更改了HOG的cellsize导致特征大小与初始化时不同，失败。修改后就能用了。

我是在SSE.hpp中#define USE_NEON和feature_extractor.hpp中#define USE_SIMD，编译器设置
-DUSE_SIMD -DUSE_NEON -ffast-math -flto -mfpu=neon 来运行NEON优化的。但是运行中出现了问题。

首先，在速度上，优化后提取一次特征用时40ms以上，没优化前20ms左右；（单尺度，骁龙660）
其次，在正确性上，优化后得到的pos点是不正确的，一直飘。

我看了HOG特征中的数据，看着是挺正常的，大小和channel也都正常，是不是我这样的设置方式不太妥？
另外速度居然还没有优化前快，难道是CPU已经到极限了？

**Comment by TCBocean** [comment]
我对比了一下我的feature_extractor.hpp文件后，发现有提取特征的函数与最新版除了修复BUG的地方，还有两处不同，可能是我的版本比较老了吧。我修改了那两处后，结果正常了。但是速度还是没优化前快。emmmmmmmmmmm....

**Comment by rockkingjy** [comment]
@TCBocean Sorry, I am not be able to help you with only these information. I have tested on intel i9 i7 TX2(armA57/2), and raspberry pi3, not on any cell phone. Normally it should work, but not quite sure of it.

**Comment by TCBocean** [comment]
我看了一下函数的运行时间，gradMag耗时28ms左右，fhog耗时7ms左右。单就gradMag这个函数的速度就没有NEON优化前直接提取HOG特征快。

**Comment by TCBocean** [comment]
程序能正常跑了，我看了一下函数的运行时间，gradMag耗时28ms左右，fhog耗时7ms左右。单就gradMag这个函数的速度就慢于NEON优化前直接提取HOG特征。
我对安卓的NEON优化是一窍不通，程序明明能运行NEON优化，但是速度就是上不去，很让人懊恼

**Comment by rockkingjy** [comment]
@TCBocean It seems that the NEON does not work correctly on your cellphone.

**Comment by TCBocean** [comment]
有一件事情我想弄明白，就是程序的确是用的get_hog_features_simd函数来提取特征，并且提取成功了，应该能够说明NEON指令优化是能够使用的把？
难道是NEON不能使用的情况下运行程序，CPU会自动把它变为普通代码吗？

**Comment by rockkingjy** [comment]
Normally speaking, the neon is already used. The speed's limitation might comes from the memory latency.

**Comment by TCBocean** [comment]
你好，请问你使用了FFTW后对速度提升有帮助吗，树莓派上一帧能提升多少毫秒？
我正打算在安卓平台上编译FFTW，后来我发现程序中需要用到fft的地方占用时间都很短，所以我在考虑还有没有必要做FFTW。

**Comment by rockkingjy** [comment]
@TCBocean  don't need to use FFTW, it doesn't help so far.

**Comment by TCBocean** [comment]
嗯，谢谢你的回答

**Comment by TCBocean** [comment]
我不知道我做了什么，看了好多论坛帖子后，瞎改了一些编译选项，也不知道是哪个起了作用，然后NEON优化在安卓上成功起飞。哈哈哈哈哈....  现在没有尺度一帧只要18ms左右

**Comment by rockkingjy** [comment]
@TCBocean Congratulations! If you could contribute to the open source repository, that will be wonderful!

**Comment by TCBocean** [comment]
你好，我似乎发现一个BUG，就是当选取的目标竖向比较长的时候，并且reg疏密化阈值设为0.15，会出现reg变成列向量的情况，这导致在初始化训练的时候，lhs函数中，4.里的reg_pad会没有大小，训练出错。MATLAB正常的效果应该得到的是一个行向量（比如OTB中的David3）。
这是因为OpenCV的dft与Matlab效果不大一样造成的吗？

**Comment by rockkingjy** [comment]
@TCBocean yes, I've already found it and updated just now.

**Comment by TCBocean** [comment]
可以啦！~

**Comment by mawnja** [comment]
初始化时间太长，如果改成多目标跟踪，耗时爆表！

**Comment by TCBocean** [comment]
> 初始化时间太长，如果改成多目标跟踪，耗时爆表！

我在骁龙660上，HOGcellsize=6，CNcellsize=4（自己加的），FDSST的HOGcellsize=4，5个尺度插值到33个尺度（自己加的），初始化一次1300ms，运行速度35ms/帧，我对这个速度还是挺满意的。
ECO算法本身是针对单目标的，多目标跟踪应该考虑使用其它的算法。

**Comment by TCBocean** [comment]
@rockkingjy  你好，我今天发现一个问题就是程序跑的时间越久占用的RAM越多，似乎并不会自动释放掉。我找了很久也不知道是我的安卓接口问题还是ECO程序问题。所以我想问一下，你平时测试程序的时候，内存会不会有越用越多直到溢出的情况？

**Comment by TCBocean** [comment]
@rockkingjy  挺老了，是8月13日的版本。你更新的bug我都有手动更新，所以应该与最新版本相近。

**Comment by TCBocean** [comment]
@rockkingjy 不好意思，给你带来麻烦了。我找到原因了，不是ECO程序问题，是我安卓这边读完图片以后有个指针没释放，导致内存溢出了。

**Comment by rockkingjy** [comment]
@TCBocean That's fine, enjoy your week-end!

**Comment by TCBocean** [comment]
你好，我又发现个问题。就是线程资源似乎不会被释放。因为在我解决了我原来内存溢出问题后，运行时间是变长了，但是运行一段时间后还是会卡死。我查看Log发现每次都是在线程里面出问题。后来我去百度以后发现是线程资源没有被释放造成的（这个资源没释放居然没有体现在运存上）。我在线程函数里面加了pthread_detach(pthread_self());后就可以运行很久很久很久了.......
理论我是参照这篇文章的 https://blog.csdn.net/love_gaohz/article/details/41747193

**Comment by rockkingjy** [comment]
@TCBocean yes, it should be released, I've done it already in file 'runecohtracker.cc' already.

**Comment by TCBocean** [comment]
@rockkingjy  原来如此！
我的工程里没有使用runecotracker.cc，难怪会出现没释放的情况。

**Comment by rockkingjy** [comment]
@TCBocean I've checked a bit again, yes, you are right, it's better to add the code as you mentioned, thank you.

**Comment by TCBocean** [comment]
@rockkingjy you're welcome

**Comment by NickLi0627** [comment]
@TCBocean Hi, I'm also working on 660 device and have the same problem as you face before. (Neon doesn't speed up the whole process). I wonder know what kind of flag you changed? Thanks

**Comment by TCBocean** [comment]
@AsusAlexLi 
Hello, I'm building a project using Android Studio. I added an instruction "set (CMAKE_BUILD_TYPE Release) to the “cmakelist“ file before I successfully turned on NEON optimization.
My flag is "-std=c++11 -frtti fexceptions -fopenmp -mfpu=neon -mfloat-abi=softfp -O3 -ffast-math".
I hope it will help you.

**Comment by NickLi0627** [comment]
@TCBocean Thanks a lot, I have already enabled NEON and speed up the tracker successfully !
As you said, "set (CMAKE_BUILD_TYPE Release)" does help.

**Comment by qq297110281** [comment]
@TCBocean  可以请问一下你移植到android 运行使用的是什么环境？比如： NDK是什么版本，Android版本是多少？或者移植的时候需要什么特殊的配置？ 我尝试移植，编译是没什么问题，但是一运行起来就闪退。可以告知一下么？

**Comment by TCBocean** [comment]
@qq297110281 这个需要看一下你的具体报错的log信息才能做判断，我在使用的时候并没有出现有关环境上的配置问题，一般都是代码本身存在一些问题。

**Comment by qq297110281** [comment]
@TCBocean  谢谢回复。我解决了运行的问题，我的NDK版本不对导致，下载已经修复可以运行。但是我测试运行速度并没有能达到你说 35ms/帧。 基本上一帧需要 70ms左右。我的编译参数参考你贴出来的：
set (CMAKE_BUILD_TYPE Release)
#-DUSE_FFTW
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -frtti -fexceptions -fopenmp -mfpu=neon -mfloat-abi=softfp -O3 -ffast-math -DUSE_SIMD -DUSE_NEON   -pthread  -DUSE_MULTI_THREAD")
 然后配置参数：
        eco::EcoParameters parameters;
        parameters.useDeepFeature = false;
        parameters.useHogFeature = true;
        parameters.useColorspaceFeature = false;
        parameters.useCnFeature = true;
        parameters.useIcFeature = true;
        parameters.learning_rate = 0.01;
        parameters.projection_reg = 5e-7;
        parameters.init_CG_iter = 10 * 20;
        parameters.CG_forgetting_rate = 60;
        parameters.precond_reg_param = 0.2;
        parameters.reg_window_edge = 4e-3;
        parameters.use_scale_filter = false;
        parameters.hog_features.fparams.cell_size=12;
        parameters.cn_features.fparams.cell_size = 10;
        parameters.ic_features.fparams.cell_size = 10;
我跑的时候使用的图片分辨率是 384x216
不知有没有什么优化加速的建议？？？

**Comment by TCBocean** [comment]
@qq297110281 我印象中，我只是用了HOG和CN两种特征，用线程并行提取的。在算法实现上也做了些优化，比如多用NEON、指针和多线程。还有模型更新、模型训练这些操作也用线程运行，我印象中原来代码中的模型更新有个地方相当耗时，优化一下实现方式可以提升很多速度。
我的使用的代码版本很老了，后来新加的IC特征什么的我都没有使用。

**Comment by NiYien** [comment]
@TCBocean 你好，请问能加QQ跟你联系吗？对你这个安卓的项目非常感兴趣~~这是我的qq，362153154

**Comment by TCBocean** [comment]
@HiDream 抱歉，当初只是想练练手，项目已经被我删除了。如果你在运用中遇到什么问题就在这问我就可以了~

**Comment by HiDream** [comment]
感谢回复！我是自己做的产品，很早以前是用的tld在android部署的，现在没有太多精力搞这个。请问方便留个联系方式吗，感觉你很厉害啊，可以合作做产品啊
。我是打算将Fairmot移植到移动端的，但是真的找不到像你这样，原理和编程能力都这么强的！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TCBocean"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:43
收件人:&nbsp;"rockkingjy/OpenTracker"<OpenTracker@noreply.github.com&gt;;
抄送:&nbsp;"何俊"<362153154@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rockkingjy/OpenTracker] 为什么我在安卓手机上用NEON优化后的程序，比没优化前的程序还慢 (#11)





 
@HiDream 抱歉，当初只是想练练手，项目已经被我删除了。如果你在运用中遇到什么问题就在这问我就可以了~

**Comment by TCBocean** [comment]
@HiDream emmmmmm谢谢你的夸奖，其实我也没有那么厉害啦。另外我对现在的工作挺满意的，没有想要换别的工作。

**Comment by HiDream** [comment]
emmmm，没关系~就是闲暇的时候，交流交流就好了~------------------ 原始邮件 ------------------
发件人: "TCBocean"<notifications@github.com>
发送时间: 2020年4月23日(星期四) 晚上8:31
收件人: "rockkingjy/OpenTracker"<OpenTracker@noreply.github.com>;
抄送: "HiDream"<362153154@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rockkingjy/OpenTracker] 为什么我在安卓手机上用NEON优化后的程序，比没优化前的程序还慢 (#11)




 
@HiDream emmmmmm谢谢你的夸奖，其实我也没有那么厉害啦。另外我对现在的工作挺满意的，没有想要换别的工作。
 
&mdash;

**Comment by NiYien** [comment]
@TCBocean 你好，请问你之前编译的时候有遇见这个警告吗？
clang++: warning: argument unused during compilation: '-mfloat-abi=softfp' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]

**Comment by TCBocean** [comment]
@HiDream 这个我倒没有注意过，我用android studio编译的，只要没报错我都没去理会

**Comment by YoungHong1992** [comment]
谢谢老哥，set (CMAKE_BUILD_TYPE Release) 真的管用！
