### ISSUE TITLE
There are some problems when using ECO::reset() for retracking

### ISSUE THREAD

**Issue by ywdu** [rockkingjy/OpenTracker#12]
When I want to change the tracking target by using ECO::rset(), the "max_score: nan" will continue to occur during tracking.

**Comment by rockkingjy** [comment]
@ywdu  yes, bug fixed.

**Comment by ywdu** [comment]
Thank you for your work, I tried to replace the target with your modified eco::init, but the performance is not good compared to the first time using eco::init. I guess the reason maybe that the previous tracking target was not clean up fully, so it affected retracking.

**Comment by ywdu** [comment]
Thank you very much for your reply, I tried it again, the new eco::init can perfectly work in the task of retracking，congratulations!
Looking forward to your further work! If the tracking stability of this version ECO can be improved same as  the author's MATLAB code, it will be perfect.
