### ISSUE TITLE
accuracy question about the eco 

### ISSUE THREAD

**Issue by wangnet** [rockkingjy/OpenTracker#13]
i have tested with the bothe caffe+cuda and just hog feature, works well, so thanks ~

what about the eco tracker accuracy  compare with eco of (https://github.com/martin-danelljan/ECO)

**Comment by rockkingjy** [comment]
@wangnet  I am testing it recently, I will add to the readme when I finish this.

**Comment by rockkingjy** [comment]
@wangnet Tested and the result on readme.md.
