### ISSUE TITLE
add cn feature complete？

### ISSUE THREAD

**Issue by Oliverwang** [rockkingjy/OpenTracker#14]
Download the latest code, the result is wrong, turn off the cn feature is right

**Comment by rockkingjy** [comment]
@Oliverwang it should work, have you changed the address of CNnorm.txt in parameters.hpp to your settings?

**Comment by Oliverwang** [comment]
@rockkingjy  Oh, my god, I forgot to set the address of CNnorm.txt，Thank you

**Comment by rockkingjy** [comment]
@Oliverwang hard to say, are all the parameters the same in the parameters.hpp and runecotracker.cc?

**Comment by Oliverwang** [comment]
@rockkingjy  Except for the extra parameters of the new version, everything else is the same.I tested it with the same video, the new version is more unstable.

**Comment by Oliverwang** [comment]
@rockkingjy   hog feature only      
min_image_sample_size = max_image_sample_size = 10000
number_of_scales = 1
use_scale_filter = false

**Comment by Oliverwang** [comment]
@rockkingjy In the new version, the tracking frame will jump suddenly during the tracking process and track to a place other than the target. I calculated the average value of the initialization time, almost

**Comment by rockkingjy** [comment]
@Oliverwang  yes, you are right, a bug in commit 046de329cae6d5865d92465ea3aa9ed9ef96a212, I will update later.

**Comment by rockkingjy** [comment]
@Oliverwang  updated, have a check if it works well.

**Comment by Oliverwang** [comment]
@rockkingjy  The current version tracking is very good,everything is ok. thank you
