### ISSUE TITLE
我发现了两个ECO在安卓手机上的BUG，并已经把它们解决了

### ISSUE THREAD

**Issue by TCBocean** [rockkingjy/OpenTracker#16]
1.gradient.cpp中的gradHist函数中指针的索引有的时候会出现异常值，我也不清楚原因，这是个随机性BUG，并且处理器越好的手机，发生这个BUG的可能性越大，（难道是处理速度太快了，指针调用没跟上？）。我对所有需要用索引的地方（比如H0[O0[y]+1]+=ms[1]*M0[y];）都对他们的索引进行检查（比如检查O0[y]和y的值），如果出现异常直接continue，这个BUG就没有再出现过了。
2.在ffttools.cpp中的magnitude函数，在cv::split(img, planes);时有的时候会出现分解不出结果的情况（planes.size()=0;但是分解前channel=2），这个问题也是概率出现，不知道是不是因为输入变量加了const导致的。我在函数开始时建了一个Mat，然后把img给copyTo过去，再用这个新的Mat进行分解，这个BUG就没有再出现过了。（我用的OPENCV版本是3.4.0）

以上是我在安卓上发现的BUG，不知道你在别的平台有没有遇到过。

**Comment by TCBocean** [comment]
第二个BUG经过多次测试还是会出现，很尴尬

**Comment by rockkingjy** [comment]
@TCBocean  These problems I might be encountered before and fixed if my memory is correct, now never happened again. Is your version the same as mine?
