### ISSUE TITLE
eco tracker error

### ISSUE THREAD

**Issue by tomorrow0911** [rockkingjy/OpenTracker#18]
I tried Quick Run ECO Tracker --ubuntu, but I get an error like the one below and it will end on the way.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

or

OpenCV Error: Assertion failed (0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols) in Mat, file /home/satlab/opencv-3.3.1/modules/core/src/matrix.cpp, line 501
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/satlab/opencv-3.3.1/modules/core/src/matrix.cpp:501: error: (-215) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function Mat

**Comment by rockkingjy** [comment]
have you changed the path for CN feature in parameters.h?

**Comment by tomorrow0911** [comment]
I have not changed CN feature in parameters.h.

**Comment by rockkingjy** [comment]
do you use cn feature? if yes, need to change to your path.

**Comment by tomorrow0911** [comment]
I want to run Quick Run ECO Tracker. 
I changed makefile, runecotracker.cc, parameters.hpp as explained.
Below is the execution result.

1 205 151 17 50 
../sequences/Crossing/img/0001.jpg
max_score_threshhold: 0.100000
0:1.000000; 
Frame:1 FPS:193.946
iou:0.788021
Frame:2 FPS:171.969
iou:0.594808
Frame:3 FPS:221.494
iou:0.494162
Frame:4 FPS:214.872
iou:0.412184
Frame:5 FPS:218.38
iou:0.194059
Frame:6 FPS:102.924
iou:0.194935
Frame:7 FPS:194.799
iou:0.156116
Frame:8 FPS:213.223
iou:0.116446
Frame:9 FPS:210.674
iou:0.0530368
Frame:10 FPS:193.804
iou:0.0206253
Frame:11 FPS:202.402
iou:0
Frame:12 FPS:98.4871
iou:0
Frame:13 FPS:185.415
iou:0
Frame:14 FPS:175.665
iou:0
Frame:15 FPS:185.463
iou:0
Frame:16 FPS:183.628
iou:0
Frame:17 FPS:175.335
iou:0
Frame:18 FPS:90.843
iou:0
Frame:19 FPS:178.773
iou:0
Frame:20 FPS:174.009
iou:0
Frame:21 FPS:154.631
iou:0
Frame:22 FPS:162.785
iou:0
Frame:23 FPS:168.354
iou:0
Frame:24 FPS:90.2012
iou:0
Frame:25 FPS:156.564
iou:0
Frame:26 FPS:155.82
iou:0
Frame:27 FPS:157.521
iou:0
Frame:28 FPS:155.687
iou:0
Frame:29 FPS:153.278
iou:0
OpenCV Error: Assertion failed (0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols) in Mat, file /home/satlab/opencv-3.3.1/modules/core/src/matrix.cpp, line 501
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/satlab/opencv-3.3.1/modules/core/src/matrix.cpp:501: error: (-215) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function Mat

**Comment by rockkingjy** [comment]
@tomorrow0911 I've updated the readme.md, it might be that you haven't make install and don't have the correct path for cn feature. try again.

**Comment by tomorrow0911** [comment]
I can run ECO Tracker!.thank you very mach.
