### ISSUE TITLE
I want to use OpenTracker in ROS(Robot Operating System)

### ISSUE THREAD

**Issue by tomorrow0911** [rockkingjy/OpenTracker#19]
I want to use eco tracker with ros, but I need to rewrite makefile to CmakeLists.
Because I am a C ++ beginner I could not rewrite successfully, the effective speed fell to half. Please let me know if you know how to rewrite.

**Comment by rockkingjy** [comment]
@tomorrow0911  you could have a check in the example/ file.

**Comment by tomorrow0911** [comment]
I have solved this problem.Thanks for the advice
