### ISSUE TITLE
slowly when testing ECO

### ISSUE THREAD

**Issue by shenjackson** [rockkingjy/OpenTracker#20]
When I was testing ECO, there was almost no delay, but the frame rate was only about 30.
My computer is intel-i5, system linux-CentOS7

**Comment by rockkingjy** [comment]
@shenjackson Don't quite clear what you mean, if you want to run faster, because the CN feature is not yet speed-up by SIMD etc. , if just use HOG feature, the speed will faster. It can be changed in runecotracker.cc:  parameters.useCnFeature = false;

**Comment by shenjackson** [comment]
oo， I know how to solve it, thank you for your answer.  ^ - ^
