### ISSUE TITLE
FFTW slows down the algorithm!

### ISSUE THREAD

**Issue by zanazakaryaie** [rockkingjy/OpenTracker#26]
Hello

I've tested your dft function which can use FFTW. OpenCV takes 39ms to calculate dft of my image. But FFTW takes 180-190ms! Let me say that I just measured the `fftw_execute(p)` part so that matrix allocations won't be considered in calculation time.
Could you please help? I expected FFTW to be faster than OpenCV's implementation

**Comment by rockkingjy** [comment]
don't use fftw, it's slower as I tested, if you could find a way out to speed up with it, that will be great.
