### ISSUE TITLE
there is a error when run  ecotracker.bin

### ISSUE THREAD

**Issue by ou-zhi-hui** [rockkingjy/OpenTracker#27]
[~/share/tracking/OpenTracker/eco]$ ./runecotracker.bin                                                                                               [master]
1 205 151 17 50
../sequences/Crossing/img/0001.jpg
max_score_threshhold: 0.100000
0:0.970590; 1:0.980296; 2:0.990099; 3:1.000000; 4:1.010000; 5:1.020100; 6:1.030301;
Frame:1 FPS:50.8075
iou:0.794821
Frame:2 FPS:57.7728
iou:0.600735
Frame:3 FPS:63.9741
iou:0.497778
Frame:4 FPS:63.936
iou:0.408577
Frame:5 FPS:63.9623
iou:0.18273
Frame:6 FPS:63.0413
iou:0.180562
Frame:7 FPS:62.6116
iou:0.138218
Frame:8 FPS:62.6241
iou:0.096313
Frame:9 FPS:59.5788
iou:0.0511876
Frame:10 FPS:62.3493
iou:0.0328268
Frame:11 FPS:58.1977
iou:0
Frame:12 FPS:57.9719
iou:0
Frame:13 FPS:58.1826
iou:0
Frame:14 FPS:57.7413
iou:0
Frame:15 FPS:58.1107
iou:0
Frame:16 FPS:59.2547
iou:0
Frame:17 FPS:55.4815
iou:0
Frame:18 FPS:55.1005
iou:0
Frame:19 FPS:55.2519
iou:0
Frame:20 FPS:54.2799
iou:0
Frame:21 FPS:53.277
iou:0
Frame:22 FPS:54.8815
iou:0
Frame:23 FPS:51.8867
iou:0
Frame:24 FPS:53.6728
iou:0
Frame:25 FPS:54.2151
iou:0
Frame:26 FPS:53.7847
iou:0
Frame:27 FPS:52.5177
iou:0
Frame:28 FPS:51.9536
iou:0
Frame:29 FPS:51.0908
iou:0
**runecotracker.bin: sample_update.cc:284: void eco::SampleUpdate::update_distance_matrix(cv::Mat&, float, int, int, float, float): Assertion `0 && "error: alpha1 or alpha2 equals 0"' failed.
[1]    22526 abort (core dumped)  ./runecotracker.bin**

**Comment by rockkingjy** [comment]
That's might be that you didn't make install or have the wrong path for the CN feature. 
To make it simple for use without the same issue again, I will update in a few minutes. You could have a try later.

**Comment by ou-zhi-hui** [comment]
thank you
