### ISSUE TITLE
speed to test

### ISSUE THREAD

**Issue by ou-zhi-hui** [rockkingjy/OpenTracker#29]
hi, i write the cmakelist to replace makefile to compile, but code and configuration is not changed,the result are as follows:

|||
|--|--|
|cmakelist|Frames:119 AvgPrecision:1 AvgIou:0.669755 SuccessRate:0.957983 IniFps:2.47154 AvgFps:100.776|
|makefile|Frames:119 AvgPrecision:1 AvgIou:0.715986 SuccessRate:1 IniFps:2.35872 AvgFps:44.9528
|hardware|model name      : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

the speed is more faster,but IOU is decline,do you know what reasons for this result?

**Comment by rockkingjy** [comment]
sorry, just from the information you gave, could not figure out the reason. have you changed anything else in the code?

**Comment by ou-zhi-hui** [comment]
there is nothing to changes in code and only add cmake support for eco

**Comment by rockkingjy** [comment]
there might be something tricky in cmake, could you make a pull request and I will check it tomorrow.

**Comment by ou-zhi-hui** [comment]
i am alreadly fork you and push some changes, can you see that?

**Comment by rockkingjy** [comment]
I will check tomorrow.

**Comment by ou-zhi-hui** [comment]
**I test eco source code on tx2， AvgFps is about 14**，but your test result is 34，so is there some special setting or configuration?

Frame:108 FPS:5.09502
iou:0.713023
Frame:109 FPS:16.694
iou:0.785394
Frame:110 FPS:16.4223
iou:0.777419
Frame:111 FPS:16.397
iou:0.769267
Frame:112 FPS:16.4511
iou:0.77757
Frame:113 FPS:16.3479
iou:0.719558
Frame:114 FPS:5.13487
iou:0.740479
Frame:115 FPS:16.4079
iou:0.717312
Frame:116 FPS:16.347
iou:0.77833
Frame:117 FPS:16.3912
iou:0.770209
Frame:118 FPS:16.334
iou:0.818428
Frame:119 FPS:16.3148
iou:0.711288
Frame:120 FPS:5.14017
**Frames:119 AvgPrecision:1 AvgIou:0.724475 SuccessRate:1 IniFps:1.05653 AvgFps:14.7278**

**Comment by rockkingjy** [comment]
For the difference of IOU, just because you set:
set(SIMD 1), if set to 0, it will the same.
And using SIMD not necessary means that it will decline the result, even it declines a bit here in the demo. I've tested it on VOT, with SIMD performs better than without in VOT datasets.

**Comment by rockkingjy** [comment]
For the speed of TX2, hard to say, different parameters and settings affects, even a bit of changement on the makefile also could affects. You could try it out.

**Comment by ou-zhi-hui** [comment]
- `For the difference of IOU, just because you set: set(SIMD 1), if set to 0, it will the be same.`
You means that each test result will be diffrent if using SIMD？But the above result with same setting(e.g SIMD=1)，many test results indicate IOU with CMakeList below than makefile，but speed is just the opposite.
- `And using SIMD not necessary means that it will decline the result, even it declines a bit here in the demo. `
You means the performance will **decline** if using SIMD?
- `I've tested it on VOT, with SIMD performs better than without in VOT datasets.`
You means the performance will  **better** if using SIMD?
so,i'm so sorry to not understand that your means about what you say.

**Comment by ou-zhi-hui** [comment]
- `For the speed of TX2, hard to say, different parameters and settings affects, even a bit of changement on the makefile also could affects. You could try it out.`
Do you know some tricks in makefile settings？Can you share with me ? thanks/.

**Comment by ou-zhi-hui** [comment]
Do you know the diffrence of speed between cmake and makefile？

**Comment by rockkingjy** [comment]
Okay, the results here using the updated OpenTracker:
using makefile(smid=0):   AvgPrecision:1 AvgIou:0.724257 SuccessRate:1 IniFps:2.78031 AvgFps:46.0486
using cmake(set(simd 0)):   AvgPrecision:1 AvgIou:0.721458 SuccessRate:1 IniFps:2.84737 AvgFps:55.8872
There are some small difference of speed, yes, but not that large as yours(>2 times). You could have a test directly on my updated OpenTracker.

**Comment by ou-zhi-hui** [comment]
I tested just now with source code from github,the result as follows:（**note**:cmakelist MULTI_THREAD=ON，makefile MULTI_THREAD=OFF）

**makefile:**
- Frames:119 AvgPrecision:1 AvgIou:0.715986 SuccessRate:1 IniFps:2.59503 AvgFps:45.3497
- Frames:119 AvgPrecision:1 AvgIou:0.715986 SuccessRate:1 IniFps:2.53105 AvgFps:45.2489
- Frames:119 AvgPrecision:1 AvgIou:0.715986 SuccessRate:1 IniFps:2.34064 AvgFps:45.0879
**cmakelist:**
- Frames:119 AvgPrecision:1 AvgIou:0.739201 SuccessRate:1 IniFps:2.46443 AvgFps:49.8564
- Frames:119 AvgPrecision:1 AvgIou:0.739145 SuccessRate:1 IniFps:2.4568 AvgFps:49.5886
- Frames:119 AvgPrecision:1 AvgIou:0.739004 SuccessRate:1 IniFps:2.46872 AvgFps:50.3747

**there is some difference of speed when train** as follows:
makefile:
**Frame:108 FPS:14.5318**
iou:0.708435
Frame:109 FPS:49.909
iou:0.708262
Frame:110 FPS:50.7206
iou:0.757344
Frame:111 FPS:50.4787
iou:0.661206
Frame:112 FPS:50.1779
iou:0.700819
Frame:113 FPS:50.0029
iou:0.693824
**Frame:114 FPS:14.6386**
iou:0.723565
cmakelist
**Frame:108 FPS:49.2808**
iou:0.731536
Frame:109 FPS:49.9077
iou:0.790029
Frame:110 FPS:50.4684
iou:0.719607
Frame:111 FPS:51.0725
iou:0.661206
Frame:112 FPS:51.7931
iou:0.698921
Frame:113 FPS:50.6027
iou:0.716928
**Frame:114 FPS:49.1778**
iou:0.737286

**Comment by ou-zhi-hui** [comment]
I see, the speed will faster about 2 times when using SIMD，the trainig time will less about 4 times when using multi_thread.
thank for your help!

**Comment by rockkingjy** [comment]
you are welcome.
