### ISSUE TITLE
when I  "make all " ,there are some errors

### ISSUE THREAD

**Issue by DK-tech** [rockkingjy/OpenTracker#30]
inputs/openpose.cc:412:113: error: cannot convert ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’ to ‘int’ for argument ‘6’ to ‘std::pair<op::ProducerType, std::__cxx11::basic_string<char> > op::flagsToProducer(const string&, const string&, const string&, int, bool, int)’
                         (unsigned int)FLAGS_3d_views, FLAGS_flir_camera_index);
                                                                              ^
inputs/openpose.cc:436:13: error: ‘op::Wrapper {aka op::WrapperT<std::vector<op::Datum> >}’ is not a template
         op::Wrapper<std::vector<UserDatum>> opWrapper;
             ^
inputs/openpose.cc:444:19: error: ‘op::Wrapper {aka class op::WrapperT<std::vector<op::Datum> >}’ has no member named ‘setWorkerOutput’
         opWrapper.setWorkerOutput(wUserOutput, workerOutputOnNewThread);
                   ^
inputs/openpose.cc:472:52: error: no matching function for call to ‘op::WrapperStructInput::WrapperStructInput(<brace-enclosed initializer list>)’
             FLAGS_frame_rotate, FLAGS_frames_repeat};
                                                    ^

**Comment by rockkingjy** [comment]
That relates to your openpose version, it might be updated recently. You could try my forked version, or try to change the openpose.cc to comply to your version.

**Comment by DK-tech** [comment]
which version did you used?There were same errors ,when I tried to use openpose V1.3.Such as
inputs/openpose.cc:412:113: error: too many arguments to function ‘std::shared_ptr<op::Producer> op::flagsToProducer(const string&, const string&, const string&, int, bool, const string&, double, const string&, unsigned int)’
                         (unsigned int)FLAGS_3d_views, FLAGS_flir_camera_index);

**Comment by rockkingjy** [comment]
you could try this version: https://github.com/rockkingjy/openpose

**Comment by rockkingjy** [comment]
sorry, can't tell just by this information.

**Comment by rockkingjy** [comment]
seems you've solved the problem, I close this issue.

**Comment by kxhit** [comment]
@DK-tech Hi! I meet the same error. Have you figure it out? Thanks!
