### ISSUE TITLE
ECO::init is time consuming

### ISSUE THREAD

**Issue by ywdu** [rockkingjy/OpenTracker#31]
Compared with ECO::update, ECO::init takes too much time to run. It will make retracking( Using ECO::init multiple times to change targets) become very hard.

**Comment by rockkingjy** [comment]
yes, init has lots of stuffs to be done, so needs time.

**Comment by isgursoy** [comment]
So what can we do? There should be a feasible way to reinitialize target, right?
Ideally, we should reinitialize tracker as often as possible.

**Comment by isgursoy** [comment]
Because of multithread bug init takes up to a second, 650 when threaded.

**Comment by isgursoy** [comment]
@rockkingjy
