### ISSUE TITLE
questions about feature_extractor.cc

### ISSUE THREAD

**Issue by yanliu837** [rockkingjy/OpenTracker#36]
In the line 230 of file feature_extractor.cc, it is sure that row and column are represented by i and j respectively, but the right of the "=" is ims.at(j, i), which show the position of a pixel, if h != w, it will be wrong!

**Comment by rockkingjy** [comment]
I'm afraid that's not the case, the gradMag is col-major which is the same as matlab, but opencv is row-major, so it needs to be rearranged. Have you test it in reality?

**Comment by yanliu837** [comment]
I'm trying to add fDSST to current eco, and I tried, if h!=w, there are bugs.

**Comment by rockkingjy** [comment]
Aha, seems u r right, how about change to this:
```
		for (int i = 0; i < h; i++)
			for (int j = 0; j < w; j++)
			{
				*(I + j * h + i) = (float)ims[k].at<cv::Vec3b>(i, j)[2];
				*(I + h * w + j * h + i) = (float)ims[k].at<cv::Vec3b>(i, j)[1];
				*(I + 2 * h * w + j * h + i) = (float)ims[k].at<cv::Vec3b>(i, j)[0];
			}
```

**Comment by yanliu837** [comment]
Yes, I changed it like this, too.
And I have finished the framework of fDSST for ECO according to the original matlab code (based on the scale_filter.cpp that unfinished), but I'm confused with the interface that you left. To be exact, scale_filter_track calls extract_scale_sample to get an cv::Mat, while the extract_scale_sample where you left is the type of vector<cv::Mat>, do I need to change the format? Or it seems that FeatureExtractor::extractor can be used there? Hurry for your help!

**Comment by yanliu837** [comment]
Well, it means that I need to change the format vector<cv::Mat> (come from feature_extractor.hog_feature_normalization) to the format of cv::Mat?

**Comment by rockkingjy** [comment]
I still don't understand your question. anyway, all the functions in scale_filter.cc is not finished and tested, you could change it as you wish, but in feature_extractor.cc, better not change anything.

**Comment by yanliu837** [comment]
Ok, thanks!
