### ISSUE TITLE
Support Opencv4

### ISSUE THREAD

**Issue by dongxuanlb** [rockkingjy/OpenTracker#41]
HI rockkingjy

since Opencv4 , "A lot of C API from OpenCV 1.x has been removed."
so when I use openvino r4, the opencv has no 1.x header.
`fhog.hpp:123:26: error: \u2018IplImage\u2019 does not name a type
 int getFeatureMaps(const IplImage *image, const int k,
`
is any plan to update the code?

**Comment by isgursoy** [comment]
Add

```
#include <opencv2/imgproc/imgproc_c.h>
#include <opencv2/core/types_c.h>
```

**Comment by dongxuanlb** [comment]
> Add
> 
> ```
> #include <opencv2/imgproc/imgproc_c.h>
> #include <opencv2/core/types_c.h>
> ```

@isgursoy 3q, it works!

**Comment by isgursoy** [comment]
I am not sure everything is fine in cv4. See https://github.com/nicewsyly/ECO/issues/22
Same with this code.
