### ISSUE TITLE
Plan to support intel NCS2?

### ISSUE THREAD

**Issue by boyiss** [rockkingjy/OpenTracker#46]
Hi, rockkingjy！

Is there a plan to supports the intel Neural Compute Stick 2?
https://software.intel.com/en-us/neural-compute-stick

**Comment by rockkingjy** [comment]
I think just the dnn feature extraction need this stick, so yes, we might do it, but not in the plan yet.

**Comment by boyiss** [comment]
Wow, good news, thank you！
