### ISSUE TITLE
eco runecotracker.bin cannot run

### ISSUE THREAD

**Issue by taiwan1frog** [rockkingjy/OpenTracker#5]
After I success to make the runecontracker.bin, I cannot run the bin and show the error below.
How can I resolve this problem. Thank you.
![image](https://user-images.githubusercontent.com/33243125/43626798-fc181336-9725-11e8-9f26-71fd9f1f42da.png)

**Comment by rockkingjy** [comment]
In makefile, set `USE_SIMD=0`, because SIMD is still in developing.
