### ISSUE TITLE
retracking

### ISSUE THREAD

**Issue by Oliverwang** [rockkingjy/OpenTracker#6]
A target tracking failure, re-tracking for another target, how to operate?      reset  Just correct the previous target

**Comment by rockkingjy** [comment]
@Oliverwang  not quit clear of your requirement, sorry.

**Comment by Oliverwang** [comment]
@rockkingjy    Thank you for your reply, I added a detection algorithm inside to track the incoming target, but repeated calls to init will be wrong, you must re-new eco class

**Comment by rockkingjy** [comment]
@Oliverwang yes, there is a bug here, I fixed it. thanks.
