### ISSUE TITLE
Error In single channel image processing?

### ISSUE THREAD

**Issue by Enigmatisms** [rockkingjy/OpenTracker#66]
I tested the speed of ECO on (Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz), with a (48, 27) ROI initially. It turned out to be about 50fps, yet I want to make it even faster (and ROI larger).
I tried to input a gray-image (in attempt to reduce computation). Though there is
```
	// Image infomations
	if (im.channels() == 3)
	{
		is_color_image_ = true;
	}
	else
	{
		is_color_image_ = false;
	}
 ```
in eco.cc, but it will crash at about line 260 after this function is called:
```
xl = feature_extractor_.extractor(im, pos_, vector<float>(1, currentScaleFactor_), params_, is_color_image_);
```
Because of the function of feature_extractor.cc (about line 368)
```
getFeatureMaps(&zz, _cell_size, &map_temp); // dimension: 27
```
In this function (in fhog.cc), cvFilter2D failed to be called.

> OpenCV Error: Assetion failed (src.size() == dst.size() && src.channels() == dst.channels()) in cFilter2D, file .../improc/src/filter.cpp, line 4968
 
Therefore I tried to revise it, for it seems that '3 channels' is set to be default. 
```
    /* originally there was only:
        dx = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 3); // single-precision floating-point, 3 channels
        dy = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 3);
    */
    if(numChannels == 1){
        dx = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 1); // single-precision floating-point, 1 channels
        dy = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 1);
    }
    else{
        dx = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 3); // single-precision floating-point, 3 channels
        dy = cvCreateImage(cvSize(image->width, image->height),
                       IPL_DEPTH_32F, 3);
    }
```
With this if statement, the problem is fixed yet there is new one "Segment fualt (core dumped)" which I failed to locate.

Just wondering whether 1 channel image could be used and how to furtherly make this faster (non-GPU). Thank you.

**Comment by valenbase** [comment]
set param.Icfeature = false;

**Comment by Zalways** [comment]
> set param.Icfeature = false;

i met same problem, when i use gray img , it crashed, and i set  param.useIcFeature = false;, it still not work.   so have you solved this problem?
@Enigmatisms

**Comment by Enigmatisms** [comment]
@Zalways No. I can't recall. The issue was posted 4 years ago and I think I haven't touched that code since then.
